workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    data-api:
        inputs:
            - location: https://glacier-api.avax.network/api-json
        overlays:
            - location: registry.speakeasyapi.dev/avalabs/avalabs/avacloud-sdk-ts-code-samples
        output: data-api/data-api.yaml
        registry:
            location: registry.speakeasyapi.dev/avalabs/avalabs/data-api
targets: {}
