name: Override Code Sample Metadata

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  replace_text:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Define the files array and apply the regex patterns
      - name: Replace lang and label in multiple files
        run: |
          # Define the list of files (both JSON and YAML)
          files=(metrics-api/metrics-api.yaml data-api/data-api.yaml)

          # Loop through files and apply regex patterns with logging
          for file in "${files[@]}"; do
            # Check if the file exists
            if [[ -f $file ]]; then
              echo "Processing $file"

              # Store the file before changes
              cp "$file" "$file.bak"

              # Apply the JSON regex pattern
              sed -i 's/"lang":\s*"typescript",\s*"label":\s*".*?"/"lang": "javascript", "label": "JavaScript"/g' "$file"

              # Apply the YAML regex pattern
              sed -i '/- lang:\s*typescript\s*\n\s*label:/ {
                N;
                s/- lang:\s*typescript\s*\n\s*label:\s*\S+/- lang: javascript\n  label: JavaScript/;
              }' "$file"

              # Check if there are changes compared to the backup
              if ! diff "$file" "$file.bak" > /dev/null; then
                echo "Changes were made to $file"
              else
                echo "No changes were made to $file"
              fi

              # Remove the backup file
              rm "$file.bak"
            else
              echo "$file does not exist"
            fi
          done
      # Step 3: Check if there are changes, and commit only if necessary
      - name: Commit and Push Changes if needed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Auto replace lang and label text in multiple files"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
